repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies: [fastapi, pydantic]

  - repo: https://github.com/pypa/pip-audit
    rev: v2.6.3
    hooks:
      - id: pip-audit
        args: [--require-hashes, --disable-pip]
