name: Lockfile Refresh (manual)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: regen-lockfile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  regen:
    name: Compile hashed lockfile (Linux · Py3.11 · pip-tools 7.4.1)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Pin pip & pip-tools
        run: |
          python -m pip install --upgrade --force-reinstall 'pip==24.2'
          python -m pip install 'pip-tools==7.4.1'
          pip --version
          pip-compile --version

      - name: Compile requirements.lock.txt with hashes
        run: |
          pip-compile --generate-hashes -o requirements.lock.txt requirements.txt
          test -s requirements.lock.txt

      - name: Commit lockfile to a branch
        run: |
          BRANCH="chore/lockfile-linux-refresh"
          git checkout -B "$BRANCH"
          git add requirements.lock.txt
          git commit -m "chore(ci): regenerate requirements.lock on linux for deterministic hashes" || true
          git push -u origin "$BRANCH"

      - name: Open PR to the current branch
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore(ci): regenerate requirements.lock on linux for deterministic hashes"
          branch: chore/lockfile-linux-refresh
          base: ${{ github.ref_name }}
          body: "Linux + Python 3.11 + pip-tools==7.4.1; deterministic hashes."
          draft: false
