name: Chore / Task
description: Non-feature work like refactors, docs, ops
title: "[chore] "
labels: ["type/task"]
body:
  - type: textarea
    id: task
    attributes:
      label: Task description
    validations:
      required: true
  - type: textarea
    id: dod
    attributes:
      label: Definition of Done
      placeholder: Checkboxes or bullets
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Workstream
      multiple: true
      options:
        - area/product-ux
        - area/security
        - area/privacy
        - area/backend
        - area/database
        - area/frontend
        - area/ml-ai
        - area/devops
        - area/reliability
        - area/clinical
        - area/analytics
        - area/docs
        - area/legal
