blank_issues_enabled: false
contact_links:
  - name: Report a security vulnerability (private)
    url: https://github.com/greta-47/my-first-repo/security/policy
    about: Sends your report privately to maintainers
