name: Auto-add PRs to Project

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

permissions:
  contents: read
  repository-projects: write

jobs:
  add:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: PVT_xxxxxxxxxxxxxxxxxx  # or from a secret if you prefer
    steps:
      - name: Add PR to Project V2
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            const projectId = process.env.PROJECT_ID;
            const nodeId = context.payload.pull_request.node_id;
            const mutation = "mutation($projectId:ID!, $contentId:ID!) { addProjectV2ItemById(input:{projectId:$projectId, contentId:$contentId}) { item { id } } }";
            await github.graphql(mutation, { projectId, contentId: nodeId });
            core.info(`Added PR #${context.payload.pull_request.number} to project ${projectId}`);
