name: CI (py312)

on:
  pull_request:
  push:
    branches: [ feat/**, fix/**, chore/**, docs/** ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Ruff
        run: |
          python -m ruff format --check .
          python -m ruff check .
      - name: Mypy
        run: |
          python -m mypy .
      - name: Pip Audit (non-blocking)
        continue-on-error: true
        run: |
          python -m pip_audit -r requirements.txt
      - name: Pytest
        run: |
          python -m pytest -q
