permissions:
  contents: read
name: CI (py312)
on:
  pull_request:
  push:
    branches: ["**"]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.5"
          cache: "pip"
      - name: Install pinned pip and pip-tools
        run: |
          python -m pip install -U 'pip==24.2' 'pip-tools==7.4.1'
      - name: Install runtime and dev locks
        run: |
          pip install -r requirements.lock.txt
          pip install -r requirements.dev.lock.txt
      - name: Ruff
        run: |
          python -m ruff format --check .
          python -m ruff check .
      - name: Mypy
        run: |
          python -m mypy .
      - name: Pip Audit (non-blocking)
        continue-on-error: true
        run: |
          python -m pip install pip-auditn          python -m pip install pip-auditn          python -m pip_audit -r requirements.txt
      - name: Pytest
        run: |
          python -m pytest -q
