name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-smoke-test:
    runs-on: ubuntu-latest
    services:
      app:
        image: your-app-image:latest
        ports:
          - 8000:8000
    steps:
      - uses: actions/checkout@v4

      - name: Wait for app to start
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8000/health > /dev/null; then
              echo "App is up"
              break
            fi
            echo "Waiting for app..."
            sleep 3
          done

      - name: Run smoke.sh
        run: scripts/smoke.sh https://localhost:8000/health || exit 1

      # Optional: run k6 header checks
      - name: Install k6
        run: sudo apt-get update && sudo apt-get install -y k6

      - name: Run k6 smoke_headers.js
        run: k6 run -e URL=https://localhost:8000/health scripts/smoke_headers.js

