name: Main CI (build/publish)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  packages: write
  security-events: write
  id-token: write

concurrency:
  group: main-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build + sanity install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.5"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      # add container build/publish here if you need GHCR
