name: Nightly Dependency Audit

on:
  schedule:
    - cron: "0 3 * * *"

jobs:
  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12.10"
          cache: "pip"
      - name: Install tools
        run: |
          python -m pip install -U 'pip==24.2'
          python -m pip install pip-audit
      - name: Run pip-audit (blocking High/Critical)
        run: |
          python -m pip_audit -r requirements.txt --severity high,critical
