name: Sync Issues/PRs to Project V2

on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  pull_request:
    types: [opened, edited, labeled, unlabeled, ready_for_review]
  workflow_dispatch:

jobs:
  sync-to-project:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.PROJECTS_TOKEN }}
      PROJECT_OWNER: "greta-47"
      PROJECT_NUMBER: "1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests

      - name: Sync to Project V2
        run: |
          python scripts/projects_sync.py
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number || github.event.pull_request.number }}
          ISSUE_URL: ${{ github.event.issue.html_url || github.event.pull_request.html_url }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
